### ISSUE TITLE
run.py not found

### ISSUE THREAD

**Issue by Macho000** [GentlebreezeZ/RACE2T#1]
I'm interested in your research paper for conducting Type Inference Research. So I tried conducting this experiment. But the run.py file does not exist in your repository. 

Could you let me get the source if it's possible. Sincerely.

**Comment by GentlebreezeZ** [comment]
Use main.py to run. It should be that you forgot the name of the file when submitting readme later, which caused you trouble. Sorry.  I will modify readme. If you are using pycharm or vscode on windows, you can run main.py directly 。
