### ISSUE TITLE
What about the torch_scatter and torch version?

### ISSUE THREAD

**Issue by leiloong** [GentlebreezeZ/RACE2T#2]
It seems that torch 2.0.4 needs torch 1.4.0.  https://data.pyg.org/whl/torch-1.4.0%2Bcu101.html  
I meet a "RuntimeError" with torch 1.8.0 and torch 2.0.4.
File "/root/RACE2T/RACE2T/layers.py", line 5, in <module>
    from torch_scatter import scatter
  File "/root/miniconda3/lib/python3.8/site-packages/torch_scatter/__init__.py", line 18, in <module>
    raise RuntimeError(
RuntimeError: Expected PyTorch version 1.4 but found version 1.8.
Which versions of torch_scatter and torch are suit your code?

**Comment by GentlebreezeZ** [comment]
As long as the torch  and torch_scatter installed normally on your computer can run. The possible cause of running error is that torch_scatter and torch  do not correspond to the version of GPU. If it doesn't, it won't work. A simple way, you can directly install torch_geometric, which will contain torch_scatter. torch_geometricis an easy-to-use library, which can easily implement graph neural network.

**Comment by GentlebreezeZ** [comment]
The library downloaded in https://data.pyg.org/whl/torch-1.4.0%2Bcu101.html may not match the GPU version. You can use PIP3 to install torch_ geometric。 At least that's how I installed it.
![Snipaste_2022-07-28_16-26-35](https://user-images.githubusercontent.com/71507997/181459685-44891553-b2f3-430a-996a-301f09690923.png)
![Snipaste_2022-07-28_16-31-32](https://user-images.githubusercontent.com/71507997/181459893-79607b03-a259-434c-b722-c4fa17acb6fb.png)

**Comment by leiloong** [comment]
Thanks a lot for your quick reply, I will try torch==1.9.0 and torch_scatter==2.0.9 now.

**Comment by GentlebreezeZ** [comment]
There is no need for all libraries to be the same. You need to match the version of the library you installed with your GPU version in order to run.

**Comment by leiloong** [comment]
Got your advice about "GPU CUDA version", thx.
I use an online Tesla P40 gpu from www.autodl.com and cuda 11.3 with torch >=1.9 (1.9, 1.10, 1.11, 1.12 checked) and torch_scatter ==2.0.9, get empty() function error.
<img width="513" alt="20399fad850c57e2152b37c4b604e4c" src="https://user-images.githubusercontent.com/9718821/181490344-305ff5a5-e7ec-4bf8-999d-faa2275eca53.png">
while I change to torch < 1.9 (1.8.1, 1.8.0, 1.5) and related lower torch_scatter version with P40 or TITAN XP,  get another error.
<img width="484" alt="5abdb6c5a8bcf839db2d8fa57ab7672" src="https://user-images.githubusercontent.com/9718821/181491106-69bcdc39-576c-4460-b34e-72f5a3a59d54.png">

Currently, I'm not sure if the online docker environment  of gpu device will lead to some conflict or I haven't get the proper version of  torch and torch_scatter or their dependencies. Have you ever meet such errors?

**Comment by leiloong** [comment]
From the document of pytorch, I notice the parameter of function torch.empty() has changed from torch 1.8.1 to after torch 1.9.
 https://pytorch.org/docs/1.8.1/generated/torch.empty.html#torch.empty
 https://pytorch.org/docs/1.9.0/generated/torch.empty.html#torch.empty
However, it is quite weird, since these functions should be part of torch package, it should be consistent itself.

**Comment by GentlebreezeZ** [comment]
I tried it on my computer, and there was no function error.
![Snipaste_2022-07-28_20-25-31](https://user-images.githubusercontent.com/71507997/181504565-51b840c1-5aba-445d-b85c-140045d3b1ad.png)
Are you running Linux or pycharm of windows? I now use pycharm of windows to run. If you are running on Linux, the parameters may be wrong, so you need to check. Because the code has been running on windows without using command line parameters, and it is directly set in the program.

**Comment by leiloong** [comment]
You are right, it is about parameters. The types of some parameters are omitted, then these parameters (int or float) are treated as string instead.(At least in linux commmand line input)
<img width="644" alt="1659062087259" src="https://user-images.githubusercontent.com/9718821/181671026-fa1ac3c4-e770-4d12-8d15-c7d40e4378b6.png">
You may update the parameter settings in config.py.
